// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsrQM5tDfkfEDuQzD56xuhxQpSVRnauWc',
    appId: '1:873278053375:web:5c0bca792f77d36d9a25ca',
    messagingSenderId: '873278053375',
    projectId: 'quotation-f6a00',
    authDomain: 'quotation-f6a00.firebaseapp.com',
    storageBucket: 'quotation-f6a00.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfpPEu4E6S3VCXCGd8LcfYGJN5mm0EHPQ',
    appId: '1:873278053375:android:667c61e503a7f6cf9a25ca',
    messagingSenderId: '873278053375',
    projectId: 'quotation-f6a00',
    storageBucket: 'quotation-f6a00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP95B8k_bSI6JtN3vvdzxfZbez5q92VLw',
    appId: '1:873278053375:ios:0e2059a50a6217f29a25ca',
    messagingSenderId: '873278053375',
    projectId: 'quotation-f6a00',
    storageBucket: 'quotation-f6a00.appspot.com',
    iosClientId: '873278053375-ijqf35vc856kra5845allub0kpu63ddb.apps.googleusercontent.com',
    iosBundleId: 'com.example.quotation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP95B8k_bSI6JtN3vvdzxfZbez5q92VLw',
    appId: '1:873278053375:ios:d5edc35f50cd22129a25ca',
    messagingSenderId: '873278053375',
    projectId: 'quotation-f6a00',
    storageBucket: 'quotation-f6a00.appspot.com',
    iosClientId: '873278053375-t1br2o5sn4bva2l04g4dfql1mebkovpg.apps.googleusercontent.com',
    iosBundleId: 'com.example.quotation.RunnerTests',
  );
}
